# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-salesforce:dev
tests:
  #  spec:
  #    - spec_path: "source_salesforce/spec.json"
  #  connection:
  #    - config_path: "secrets/config.json"
  #      status: "succeed"
  #    - config_path: "integration_tests/invalid_config.json"
  #      status: "exception"
  #  discovery:
  #    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog_rest.json"
    - config_path: "secrets/config_bulk.json"
      configured_catalog_path: "integration_tests/configured_catalog_bulk.json"
#
##  incremental: # TODO if your connector does not implement incremental sync, remove this block
##    - config_path: "secrets/config.json"
##      configured_catalog_path: "integration_tests/configured_catalog.json"
##      future_state_path: "integration_tests/abnormal_state.json"
#  full_refresh:
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_rest.json"
#    - config_path: "secrets/config_bulk.json"
#      configured_catalog_path: "integration_tests/configured_catalog_bulk.json"
