# See [Source Acceptance Tests](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/source-acceptance-tests.md)
# for more information about how to configure these tests
connector_image: airbyte/source-close-com:dev
tests:
  spec:
    - spec_path: "source_close_com/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: ["meeting_activities", "opportunity_status_change_activities", "task_completed_activities",
                      "missed_call_tasks", "email_followup_tasks", "answered_detached_call_tasks", "incoming_sms_tasks"]
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      future_state_path: "integration_tests/abnormal_state.json"
      cursor_paths:
        created_activities: ["date_created"]
        opportunity_status_change_activities: ["date_created"]
        note_activities: ["date_created"]
        meeting_activities: ["date_created"]
        call_activities: ["date_created"]
        email_activities: ["date_created"]
        email_thread_activities: ["date_created"]
        lead_status_change_activities: ["date_created"]
        sms_activities: ["date_created"]
        task_completed_activities: ["date_created"]
        leads: ["date_updated"]
        lead_tasks: ["date_created"]
        incoming_email_tasks: ["date_created"]
        email_followup_tasks: ["date_created"]
        missed_call_tasks: ["date_created"]
        answered_detached_call_tasks: ["date_created"]
        voicemail_tasks: ["date_created"]
        opportunity_due_tasks: ["date_created"]
        incoming_sms_tasks: ["date_created"]
        events: ["date_updated"]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
